//Our Twitter Credentials (not visible on Git)
var TWITTER_CONSUMER_KEY = 'N7KMv4kAyyUGx5kqzfLqAyJ5W';
var TWITTER_CONSUMER_SECRET = 'Bt99VhJrInU5KDuQussAw8738Ztl7Ds0wfsR28q5MnsBZKcESV';
var TWITTER_ACCESS_TOKEN = '1045652205448179713-e9aZNvNCWBdSh3ZTmRiJ7He9Hm3LH9';
var TWITTER_ACCESS_TOKEN_SECRET = 'Mm5ytWr1srVRNkrRL5fu1tzcuiuWMyok6rqqiQwxP7emd';



module.exports.TWITTER_CONSUMER_KEY = TWITTER_CONSUMER_KEY;
module.exports.TWITTER_CONSUMER_SECRET = TWITTER_CONSUMER_SECRET;
module.exports.TWITTER_ACCESS_TOKEN = TWITTER_ACCESS_TOKEN;
module.exports.TWITTER_ACCESS_TOKEN_SECRET = TWITTER_ACCESS_TOKEN_SECRET;
